# Generated by Django 5.2.10 on 2026-01-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chai", "0002_chaivarity_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="price",
            field=models.IntegerField(default=5, verbose_name="Chai Price"),
        ),
    ]
