# Generated by Django 5.2.10 on 2026-01-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chai", "0003_chaivarity_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaivarity",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Chai Price"),
        ),
    ]
