# Generated by Django 5.2.10 on 2026-01-23 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chai", "0005_alter_chaivarity_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaivarity",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Chai Price"
            ),
        ),
        migrations.CreateModel(
            name="chaiCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_number", models.CharField(max_length=100)),
                (
                    "issued_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("valid_until", models.DateTimeField()),
                (
                    "chai",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="chai.chaivarity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChaiReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Bad"),
                            (2, "Bad"),
                            (3, "Neutal"),
                            (4, "Good"),
                            (5, "Very Good"),
                        ]
                    ),
                ),
                ("comment", models.TextField(default="")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "chai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="chai.chaivarity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "chai_varieties",
                    models.ManyToManyField(related_name="stores", to="chai.chaivarity"),
                ),
            ],
        ),
    ]
